(defun nut_eval_arg_list (args)
  args)

(defun nut_eval (expr)
  (if (is_cons expr)
      (let ((op (car expr))
            (args (nut_eval_arg_list (cdr expr))))
        (if (is_symbol op)
            (if (int_eq (strcmp (symbol_string op) "+") 0)
                (apply_plus args)
                -1)
            -2))
      -3))
